name: Node.js CI

on: [push]

jobs:
  build:
    
    strategy:
      matrix:
        platform: [android]
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
  
    - name: Copy from dist file
      run: npx cap copy ${{ matrix.platform }}
    - run: ls -a
