name: Build

on:
  push:
    branches:
      - deploy

jobs:
  dist:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --if-present
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist
          path: dist
      
      
  build_ubuntu:
    runs-on: [ubuntu-latest]
    needs: [dist]
    
    strategy:
      fail-fast: false
      matrix:
        platform: [android, electron]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: dist
    - run: ls ./dist -a
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npx cap copy ${{ matrix.platform }}
    
    # Electron specific
    - name: Build electron
      if: matrix.platform == 'electron'
      run: |
        cd electron
        npm install
        npx electron-builder build
    - run: ls -a ./electron/dist
      if: matrix.platform == 'electron'
    - name: Upload artifact
      if: matrix.platform == 'electron'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux
        path: ./electron/dist/capacitor-app-1.0.0.AppImage
    
    # Android specific
    - name: Build apk
      if: matrix.platform == 'android'
      run: |
        chmod +x ./android/gradlew
        cd android
        ./gradlew build
        ./gradlew assembleDebug
    - name: Upload artifact
      if: matrix.platform == 'android'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Android
        path: ./android/app/build/outputs/apk/release/app-release-unsigned.apk
      
  build_macos:
    needs: [dist]
    runs-on: [macos-latest]
    strategy:
      fail-fast: false
      matrix:
        platform: [electron, ios]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: dist
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npx cap copy ${{ matrix.platform }}

      # Electron specific
      - name: Build electron
        if: matrix.platform == 'electron'
        run: |
          cd electron
          npm install
          npx electron-builder build
      - run: ls -a ./electron/dist
        if: matrix.platform == 'electron'
      - name: Upload artifact
        if: matrix.platform == 'electron'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MacOS
          path: ./electron/dist/capacitor-app-1.0.0.dmg

  app_center:
    runs-on: [ubuntu-latest]
    needs: [build_macos, build_ubuntu]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: MacOS

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: Android

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: Linux
          
      - run: |
          ls -a
          ls -a Android
          ls -a Linux
          ls -a MacOS

      - name: Upload to app-center
        uses: zackify/AppCenter-Github-Action@v1.0.0
        with:
          token: ${{ secrets.APP_CENTER_TOKEN }}
          appName: Path-Scale/Social-Soy-MacOS
          file: ./MacOS/capacitor-app-1.0.0.dmg
          group: Collaborators

      - name: Upload to app-center
        uses: zackify/AppCenter-Github-Action@v1.0.0
        with:
          token: ${{ secrets.APP_CENTER_TOKEN }}
          appName: Path-Scale/Social-Soy-Android
          file: ./Android/app-release-unsigned.apk
          group: Collaborators

        # - name: Upload to app-center
        #   if: matrix.platform == 'electron'
        #   uses: zackify/AppCenter-Github-Action@v1.0.0
        #   with:
        #     token: ${{ secrets.APP_CENTER_TOKEN }}
        #     appName: Path-Scale/Social-Soy-Linux
        #     file: ./electron/dist/capacitor-app-1.0.0.AppImage
        #     group: Collaborators

