name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        platform: [android, ios, windows, linux, macos]
        os: [macos-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ matrix.os }}
  other_job:
    runs-on: [ubuntu-latest]
    steps:
      - run: ls -a
